tasks:
  - before: >
      wget -qOdatabase-setup.sh https://codejudge-starter-repo-artifacts.s3.ap-south-1.amazonaws.com/backend-project/gitpod/php/7.1/db-gitpod-setup.sh &&
      chmod 0755 database-setup.sh &&
      bash database-setup.sh
    init: composer update && composer install && npm i && php artisan key:generate
    command: php artisan serve --host=127.0.0.1 --port=8080
ports:
  - port: 8080
    onOpen: open-preview
    visibility: public
vscode:
  extensions:
    - felixfbecker.php-debug
    - bmewburn.vscode-intelephense-client
